
# Angles
DOWN = 270
UP = 90
LEFT = 180
RIGHT = 0

# Shapes
ALIEN_SHAPE_POS = [ UP, RIGHT, DOWN, RIGHT, DOWN, RIGHT, DOWN, RIGHT, DOWN, DOWN, DOWN, LEFT, UP, UP, LEFT, DOWN, LEFT, DOWN, RIGHT, DOWN, LEFT, LEFT, UP, UP, LEFT, LEFT, DOWN, DOWN, LEFT, LEFT, UP, RIGHT, UP, LEFT, UP, LEFT, DOWN, DOWN, LEFT, UP, UP, UP, RIGHT, UP, RIGHT, UP, RIGHT, UP, RIGHT, DOWN,]
LEFT_EYE_POS  = [LEFT, UP, RIGHT]
RIGHT_EYE_POS = [DOWN, LEFT, UP]

# Colors
SCREEN_BG_COLOR = "lightblue"
ALIEN_COLOR = "orange"

# Tipography
FONT_SIZE = "Roboto", 16, "normal"

